### ISSUE TITLE
Help me make custom images for the game and my translation of arabic!

### ISSUE THREAD

**Issue by omaryomario** [elnyet/lethal_company_french_translation#1]
Hi There!
i am currently making arabic support mod to expand the language support community for the game!

i am facing an issue where i dont know how to make custom images for the main menu and that stuff.

In `Traduction_FR_de_Lethal_Company`
![image](https://github.com/elnyet/lethal_company_french_translation/assets/41876011/f2bc263b-d899-4205-bf41-6e8891fa46c7)
there is a `LogoTextV1` with something like this: `[A6946826E1-170022950F]`
i guess thats some sort of encryption for the file.
i need help in making that sort of code in that file to customize the game images in my `arabic support mod`

**Comment by elnyet** [comment]
hi ! could you send me your mod so I can check whats wrong with it ?

**Comment by omaryomario** [comment]
Oh sorry. I managed to fix the issue!
Your mod is amazing btw🤩
