### ISSUE TITLE
Aide a la traduction

### ISSUE THREAD

**Issue by Katsugami** [elnyet/lethal_company_french_translation#2]
Bonjour,

Je vous contacte pour savoir comment vous fournir des fichiers texte contenant les traductions de différents modules que j'ai traduits.

Je ne suis pas familier avec le fonctionnement de GitHub pour contribuer au projet, d'autant plus que je n'ai pas pu trouver le fichier CONTRIBUTING.md. J'ai soumis dans (Issues), mais je me demande si il y a une autre procédure que je devrais suivre.

Cordialement,

**Comment by elnyet** [comment]
bonjour !! Vous pouvez faire une pull request pour envoyer vos fichiers, je m'excuse du délai de réponse j'ai cours actuellement et je peux pas vachement travailler sur le mod en ce moment
