### ISSUE TITLE
Glowstep mod incompatible

### ISSUE THREAD

**Issue by k0bat** [elnyet/lethal_company_french_translation#4]
Le mod Glowstep ne fonctionne plus une fois la traduction FR appliqué

**Comment by elnyet** [comment]
Je peux pas y faire grand chose malheureusement, joue avec l'ordre des mods dans ton mod manager (teste de mettre le mien avant glowstep et après etc)

**Comment by k0bat** [comment]
j'ai essayer sans succès, j'ai malheureusement des connaissances très limité en code, mais je me demande quand même comment un mod de traduction peut influencer sur un mod de trace de pas, si un jour vous trouvez d'où viens le conflit je serais bien curieux de le savoir. GlowStep semble être le seul mod incompatible avec la trad en tout cas.
Et un grand merci pour le travail fournis o/

**Comment by Katsugami** [comment]
Peux tu me passée le lien du mod en question, je vais voir a regardée ci je trouve pas une solution

**Comment by k0bat** [comment]
https://thunderstore.io/c/lethal-company/p/Ozone/Glow_Steps/

Par contre une fois mort en caméra libre je vois bien les traces de pas des autres. (Ozone-BepInUtils est bien installé lui aussi)

**Comment by Katsugami** [comment]
Bonjour je Vien de testée, avec ma configuration de traduction et de modification du Fichier de config , je n'ai pas de souci

![Capture d'écran 2024-01-15 162146](https://github.com/elnyet/lethal_company_french_translation/assets/152559845/2fd7ea58-abcd-4a6a-a01f-560cd18ae360)

Voici le lien de ma configuration actuel , Récupère les traduction que j'ai mie a jour dans BepInEx\plugins\fr
Et aussi le fichier de configuration BepInEx\config\AutoTranslatorConfig.ini

Lien:https://github.com/Katsugami/lethal_company_french_translation

Remplace les actuellement dans le dossier correspondant du profile

**Comment by Katsugami** [comment]
Je viens de constater qu'il a effectué une nouvelle mise à jour de la configuration en intégrant les traductions que j'avais ajoutées ainsi que les corrections des erreurs de configuration. Tu peux la récupérer depuis la page officielle.

Lien : https://github.com/elnyet/lethal_company_french_translation

**Comment by k0bat** [comment]
Alors après vérification il me semble que ça soit le mod NewTerminal qui rentre en conflit, indépendamment du mod French Translation
