### ISSUE TITLE
Faire l'image de tricolore pour le mod AdvancedCompany by PotatoePet

### ISSUE THREAD

**Issue by Katsugami** [elnyet/lethal_company_french_translation#6]
Pourrais vous faire l'image au couleur Bleu blanc rouge pour le mode AdvancedCompany by PotatoePet

Voici la photo du menu Principal
<img width="960" alt="image" src="https://github.com/elnyet/lethal_company_french_translation/assets/152559845/230daa8d-7a8d-4ccc-a81e-ab5774e3dc10">

**Comment by elnyet** [comment]
Je vais essayer mais le problème c'est que les autres images tricolores avaient un template de base, là je crois pas qu'il y en a un + il faut que j'arrive à choper le nom exact du fichier qu'il faut mettre

**Comment by elnyet** [comment]
Par contre va falloir supprimer ça https://thunderstore.io/c/lethal-company/p/Katsugami/Audio_Non_Officielle_Traduction_FR/ ça t'appartient pas et tu réupload littéralement leur mod là sans aucune modif

**Comment by Katsugami** [comment]
Je les ai crédités dans la description ; j'ai simplement supprimé le module de traduction et conservé les fichiers audio, afin de permettre à ceux qui souhaitent uniquement disposer des fichiers audio sans la traduction
