### ISSUE TITLE
Change les modification faite perso des qu'il y a une mise a jour

### ISSUE THREAD

**Issue by Katsugami** [elnyet/lethal_company_french_translation#9]
Les traductions du fichier NewTerminal-***** devraient être séparées du mod et placées à part. Le problème est que si une personne effectue des modifications, par exemple en ajoutant des lunes, ces ajouts sont directement intégrés dans le terminal. Cependant, lorsqu'une mise à jour est effectuée, cela écrase les modifications, ce qui oblige à les refaire si aucune sauvegarde n'a été effectuée.

**Comment by elnyet** [comment]
Alors, J'ai pas vachement compris mais si t'as besoin que je le separe ça me pose pas de problème

**Comment by Katsugami** [comment]
En gros, j'avais modifié les textes du terminal pour les personnaliser, car je voulais ajouter les phases lunaires en texte. Ensuite, j'avais récupéré les traductions en français. Cependant, lorsque vous avez mis à jour le pack de traductions, cela a remplacé les textes que j'avais modifiés dans le terminal.

**Comment by Katsugami** [comment]
Je n'ai pas réussi à utiliser DeepL, il semble qu'il ne parvienne pas à effectuer la requête. Surtout, ce n'est pas pour les traductions approximatives, mais pour lancer la génération de phrases anglaises à partir de phrases françaises afin que nous puissions obtenir la syntaxe d'écriture pour la traduction. Cela pourrait vraiment nous faire gagner beaucoup de temps.

**Comment by elnyet** [comment]
redonne les parce que ça se trouve j'ai override a un moment avec mes propres fichiers
